name: Upload file to AWS s3
description: Uploads a file to as an object in an S3 bucket
inputs:
  file:
    description: The file to upload
    required: true
  bucket:
    description: The name of the bucket to upload to
    required: true
  key:
    description: The key to use for the object
    required: true
  region:
    description: The region to use for the bucket
    required: true
runs:
  using: node16
  main: dist/index.js
